Implementei Tsyringe
amandaramos-warren/Node-TS pull request #5
Opened 2022-07-06 17:26 UTC by amandaramos-warren

2022-07-06 18:05 UTC, ismaelalvesgit approved these changes

2022-07-06 18:05 UTC, ismaelalvesgit commented on src/domain/user/services/ListService.ts
> +      for (const pessoa of await this.userRepository.readAll()) {
Sugestão:
Acredito que uso do `map` nesse trecho do código ficaria mais simples
 
ex:
```js
const data = [{
  key: 1,
  name: "Pessoa",
  age: 22,
  email: "teste@teste.com"
}]

const newData = data.map((item)=>{
  const { key, name } = item
  return {
    key,
    name
  }
})

console.log(newData) // [{key: 1, name: "Pessoa"}]
```

2022-07-06 19:50 UTC, ismaelalvesgit commented on src/domain/user/helper/UserHelper.ts
> +    lista.forEach((lista) => {
Sugestão:

Acredito que fique mais simples a utilização do `includes`
```js
let data = ['teste@teste.com', 'warren@warren.com']

console.log(data.includes('warren@warren.com')) // true
```

2022-07-07 18:53 UTC, amandaramos-warren commented on src/domain/user/services/ListService.ts
> +      for (const pessoa of await this.userRepository.readAll()) {
Feito, obrigada pela sugestão

2022-07-11 17:01 UTC, ismaelalvesgit commented on src/domain/user/services/UserService.ts
> +  async criaUser (dados: IUser): Promise<IServiceResponse> {
Sugiro que adote o ingles para padrão de vairaveis, class, metodos

ex:
```js
async createUser (entity: IUser): Promise<IServiceResponse> {}
```

2022-07-11 17:27 UTC, viniciusoliveira-warren commented on src/domain/user/helper/UserHelper.ts
> +      throw new Error('Email já cadastrado')
Qual e-mail já foi cadastrado?
```suggestion
      throw new Error(`E-mail: ${email} já cadastrado!`)
```

2022-07-11 17:27 UTC, viniciusoliveira-warren commented on src/domain/user/helper/UserHelper.ts
> +  checkIfEquals (dados: string, database: IUser[]): void {
O que é dados?
```suggestion
  checkIfEquals (email: string, database: IUser[]): void {
```

2022-07-11 18:04 UTC, viniciusoliveira-warren commented on src/domain/user/services/UserService.ts
> +      if (error instanceof Error) message = error.message
Geralmente sempre teremos .message, podemos como o exemplo abaixo
```
    } catch (error: any) {
      return { code: 422, msg: error.message }
```

2022-07-11 18:14 UTC, viniciusoliveira-warren commented on src/domain/user/services/ListService.ts
> +    }
1. Recomendo dar uma olhada no artigo https://thorben-janssen.com/dont-expose-entities-in-api/ do por que não devemos mesma entidade do domínio para api
2. Não recomendo usar Partial pois pode causar uma grande confusão na typagem do código(caso real aqui da Warren)
3. 
Recomendo criar interface IUserResponse para utilizar como retorno da api
```suggestion
  async listUser (): Promise<IServiceResponse> {
    try {
      const result: IUserResponse[] = this.userRepository.database.map({ fullName, email } => {
        return {
          fullName,
          email
        }
      })
      return { code: 201, msg: result }
    } catch (error: any) {
      return { code: 422, msg: error.message }
    }
```

2022-07-11 18:16 UTC, viniciusoliveira-warren commented on src/domain/user/services/ListService.ts
> +      return { code: 422, msg: error }
De acordo com a documentação o retorno correto seria 500 e não 442 https://restfulapi.net/http-status-codes/

2022-07-11 18:17 UTC, viniciusoliveira-warren commented on src/presentation/controllers/UserController.ts
> +    res.status(criaUser.code).json(criaUser.msg)
Criação sempre será 201(Preferencialmente) ou 200, não faz sentido retornar do código
```suggestion
    res.status(201).json(criaUser.msg)
```

2022-07-11 18:18 UTC, viniciusoliveira-warren commented on src/presentation/controllers/UserController.ts
> +    res.status(criaUser.code).json(criaUser.msg)
Criação sempre será 201(Preferencialmente) ou 200, não faz sentido retornar do código
```suggestion
    const result = await this.userService.criaUser(req.body)
    res.status(201).json(result.msg)
```

2022-07-12 19:23 UTC, amandaramos-warren commented on src/domain/user/helper/UserHelper.ts
> +    if (lista.includes(dados)) {
Feito, obrigada 😄

2022-07-12 19:26 UTC, amandaramos-warren commented on src/domain/user/helper/UserHelper.ts
> +      throw new Error('Email já cadastrado')
Feito! Valeuu

2022-07-12 19:52 UTC, amandaramos-warren commented on src/domain/user/services/UserService.ts
> +      if (error instanceof Error) message = error.message
É que a ideia era tirar o any
Se eu não deixar tipar o error com any, ele dá erro. Nesse caso não tem problema o any?

2022-07-13 18:09 UTC, amandaramos-warren commented on src/domain/user/services/UserService.ts
> +  async criaUser (dados: IUser): Promise<IServiceResponse> {
Mudei o nome destes e vou ficar atenta para outros que ainda estejam em português, obrigada

2022-07-13 18:44 UTC, amandaramos-warren commented on src/domain/user/services/ListService.ts
> +export default class ListService implements IListService {
Mudei o nome dos controllers e dos services para organizar melhor o que cada um faz

2022-07-13 20:55 UTC, amandaramos-warren commented on src/domain/user/services/UserService.ts
> +      if (error instanceof Error) message = error.message
eu criei a let para contormar o problema de ter que tipar o error como any, mas consegui resolver de outra forma

2022-07-13 21:09 UTC, amandaramos-warren commented on src/domain/user/services/ListService.ts
> +      return { code: 422, msg: error }
Alterei, obrigada

2022-07-19 20:38 UTC, amandaramos-warren commented on src/presentation/controllers/UserController.ts
> +    res.status(criaUser.code).json(criaUser.msg)
Resolvido

2022-07-22 14:38 UTC, merged

2022-07-22 14:47 UTC, devjunioralveswarren requested changes

2022-07-22 14:47 UTC, devjunioralveswarren commented on src/presentation/controllers/UserListController.ts
> +  handle(req: Request, res: Response, next: NextFunction): void {
Sugiro que seja alterado o tipo void para um array de Users que é oque a função deve retornar

2022-07-22 14:47 UTC, devjunioralveswarren commented on src/presentation/controllers/UserCreateController.ts
> +  handle(req: Request, res: Response, next: NextFunction): void {
Na criação do usuário sugiro que seja retornado um objeto com as informações do usuário criado

2022-07-22 14:47 UTC, devjunioralveswarren commented on src/interfaces/presentation/IController.ts
> +  handle(req: Request, res: Response, next: NextFunction): void;
aqui tu poderia também criar uma função de error e chamar ela quando caisse no catch do controller, só uma sugestão que ficaria legal

2022-07-22 14:47 UTC, devjunioralveswarren commented on src/interfaces/domain/IUserRepository.ts
> +  create(entity: IUser): void;
mudar o tipo do retorno, aqui deve retornar um objeto do usuário criado

2022-07-22 14:47 UTC, devjunioralveswarren commented on src/interfaces/domain/IUserHelper.ts
> +  checkIfEquals(dados: string, field: keyof IUser, database: IUser[]): void;
aqui seria interessante retornar um boolean e verificar, e caso seja igual tu pode lançar um error com a mensagem 'Usuário já existe' por exemplo

2022-07-22 14:47 UTC, devjunioralveswarren commented on src/interfaces/domain/IUserCreateService.ts
> +  createUser(body: Iuser): void;
alterar o tipo do retorno

2022-07-22 14:47 UTC, devjunioralveswarren commented on src/domain/user/services/UserListService.ts
> +  listUser(): IUserListResponse[] {
optar por sempre usar o function ou public antes da função

2022-07-22 14:47 UTC, devjunioralveswarren commented on src/domain/user/services/UserCreateService.ts
> +  createUser(body: IUser): void {
alterar o tipo do retorno para um objeto do usuário criado

2022-07-22 18:43 UTC, amandaramos-warren commented on src/presentation/controllers/UserCreateController.ts
> +  handle(req: Request, res: Response, next: NextFunction): void {
eu posso estar retornando o req.body mesmo?